package chatServer.user;

import java.util.Date;

public class User {

	String UUID;
	String name;
	Date memberSince;

	protected User(){
		this.UUID = null;
		this.name = null;
		this.memberSince = null;
	}

	public User(String name){
		this.name = name;
		this.UUID = java.util.UUID.randomUUID().toString();
		this.memberSince = new Date();
	}

	public String getUUID() {
		return UUID;
	}

	public String getName() {
		return name;
	}

	public Date getMemberSince() {
		return memberSince;
	}

	public String toString(){ return this.getName(); }

	/* tests */
	public static void main(String... args){

		User user = new User("anthony");

		String name = user.getName();
		String UUID = user.getUUID();
		Date memberSince = user.getMemberSince();

		assert name.equals("anthony") : "name does not equal configured name";
		assert UUID != null : "UUID was not autogenerated";
		assert memberSince != null : "memberSince was not autogenerated";
	}


}
